import { render } from "solid-js/web"
import SessionView from "../../../src/components/session/session-view"
import { ConfigProvider, useConfig, updatePreferences } from "../../../src/stores/preferences"
import { I18nProvider } from "../../../src/lib/i18n"
import { ThemeProvider } from "../../../src/lib/theme"
import AlertDialog from "../../../src/components/alert-dialog"
import { useCommands } from "../../../src/lib/hooks/use-commands"
import { resolveResolvable } from "../../../src/lib/commands"
import { For } from "solid-js"
import { serverApi } from "../../../src/lib/api-client"
import { sseManager } from "../../../src/lib/sse-manager"
import { addInstance } from "../../../src/stores/instances"
import { sessions, setSessions, setActiveSession, setProviders } from "../../../src/stores/session-state"
import { sdkManager } from "../../../src/lib/sdk-manager"
import { loadMessages } from "../../../src/stores/session-api"
import { messageStoreBus } from "../../../src/stores/message-v2/bus"
import "../../../src/index.css"

// The native client, message loader, rendering, selection and pruning broker are real.
// Only workspace chrome is seeded; all history is generated by an isolated runtime.
const instanceId = "pruning-ui"
const sessionId = new URLSearchParams(location.search).get("session")!
const proxyPath = `/workspaces/${instanceId}/instance`
const client = sdkManager.createClient(instanceId, proxyPath)
const uiConfig = { settings: { showThinkingBlocks: true, thinkingBlocksExpansion: "collapsed", toolOutputExpansion: "collapsed", locale: "en" } }
serverApi.fetchConfigOwner = async (owner: string) => (owner === "ui" ? uiConfig : {}) as any
serverApi.fetchStateOwner = async () => ({} as any)
serverApi.patchConfigOwner = async (_owner: string, patch: any) => Object.assign(uiConfig, patch) as any
const session = await client.session.get({ sessionID: sessionId })
let eventsReady = false
addInstance({ id: instanceId, folder: session.location.directory, port: 0, pid: 0, proxyPath, status: "ready", client })
setSessions(previous => new Map(previous).set(instanceId, new Map([[sessionId, {
  ...session, instanceId, parentId: null, title: "Pruning UI fixture", agent: "build",
  model: { providerId: "fixture", modelId: "fixture" }, status: "idle", retry: null, idleSince: null,
  generationRecovery: null, runtimeStatusKnown: true, version: "1", projectID: "fixture",
  cost: 0, tokens: { input: 0, output: 0, reasoning: 0, cache: { read: 0, write: 0 } },
} as any]])))
setProviders(previous => new Map(previous).set(instanceId, [{ id: "fixture", name: "Fixture", models: [{ id: "fixture", name: "Fixture", providerId: "fixture", limit: { context: 10000, output: 1000 }, cost: { input: 0, output: 0 } }] }]))
setActiveSession(instanceId, sessionId)
function CleanupCommand() {
  const config = useConfig()
  const { commands, executeCommand } = useCommands({
    ...config, getActiveInstance: () => ({ id: instanceId, client } as any), getActiveSessionIdForInstance: () => sessionId,
  } as any)
  return <For each={commands().filter(command => command.id === "remove-session-tools-and-reasoning")}>
    {command => <button onClick={() => executeCommand(command)}>{resolveResolvable(command.label)}</button>}
  </For>
}
render(() => <ConfigProvider><I18nProvider><ThemeProvider>
  <CleanupCommand />
  <SessionView sessionId={sessionId} activeSessions={sessions().get(instanceId)!} instanceId={instanceId} instanceFolder={session.location.directory} escapeInDebounce={false} isActive={true} />
  <AlertDialog />
</ThemeProvider></I18nProvider></ConfigProvider>, document.getElementById("root")!)
;(window as any).fixture = {
  eventsReady: () => eventsReady,
  reload: () => loadMessages(instanceId, sessionId, { force: true }),
  snapshot: () => messageStoreBus.getOrCreate(instanceId).getSessionMessageIds(sessionId).map(id => messageStoreBus.getOrCreate(instanceId).getMessage(id)),
  preferences: () => updatePreferences({ showThinkingBlocks: true, thinkingBlocksExpansion: "collapsed", toolOutputExpansion: "collapsed", locale: "en" }),
}
void (async () => {
  for await (const event of client.event.subscribe()) {
    eventsReady = true
    ;(sseManager as any).handleEvent(instanceId, event)
  }
})()
