import type { SessionInfo } from "./session-state"

import { sseManager } from "../lib/sse-manager"

import {
  activeParentSessionId,
  activeSessionId,
  agents,
  clearActiveSession,
  clearActiveParentSession,
  clearInstanceSessionSelection,
  clearInstanceDraftPromptValues,
  clearInstanceDraftPrompts,
  clearSessionDraftPrompt,
  ensureSessionParentExpanded,
  getActiveParentSession,
  getActiveSession,
  getChildSessions,
  getDescendantSessions,
  getSessionRoot,
  getParentSessions,
  getSessionDraftPrompt,
  getSessionDraftPromptsForInstance,
  getAuthoritativeDraftSessionIdsForInstance,
  getAuthoritativelyDeletedSessionIdsForInstance,
  hasAuthoritativeSessionSelection,
  hydrateActiveSessionSelection,
  hydrateSessionIdleMarkers,
  hydrateSessionGenerationRecovery,
  beginSessionGenerationAdmission,
  cancelSessionGenerationAdmissions,
  getSessionFamily,
  getSessionInfo,
  getSessionMessagesLoadError,
  getSessionSearchQuery,
  getSessionSearchThreads,
  getSessionThreads,
  getThreadTotals,
  getSessions,
  getVisibleSessionIds,
  isSessionBusy,
  isSessionMessagesLoading,
  isSessionParentExpanded,
  loading,
  markSessionIdleSeen,
  markViewedSessionIdleSeen,
  providers,
  sessionInfoByInstance,
  sessions,
  setActiveParentSession,
  setActiveSession,
  setActiveSessionFromList,
  setSessionDraftPrompt,
  setSessionParentExpanded,
  setSessionStatus,
  toggleSessionParentExpanded,
  clearSessionSearch,
  getSessionHasMore,
  hydrateSessionDraftPrompt,
  isSessionSearchLoading,
  onSessionDraftHydrated,
  resetSessionPagination,
  clearInstanceDeletedSessionAuthority,
} from "./session-state"

import { getDefaultModel } from "./session-models"
import {
  createSession,
  deleteSession,
  fetchAgents,
  fetchProviders,
  fetchSessions,
  loadMoreSessions,
  searchSessions,
  forkSession,
  loadMessages,
} from "./session-api"
import {
  abortSession,
  executeCustomCommand,
  renameSession,
  runShellCommand,
  sendMessage,
  updateSessionAgent,
  updateSessionModel,
} from "./session-actions"
import {
  handleMessagePartRemoved,
  handleMessageRemoved,
  handleMessagePartDelta,
  handleMessageUpdate,
  handlePermissionReplied,
  handlePermissionUpdated,
  handleQuestionAnswered,
  handleQuestionAsked,
  handleSessionCompacted,
  handleSessionDeleted,
  handleSessionError,
  handleSessionIdle,
  handleSessionStatus,
  handleSessionUpdate,
  handleTuiToast,
} from "./session-events"

sseManager.onMessageUpdate = handleMessageUpdate
sseManager.onMessagePartUpdated = handleMessageUpdate
sseManager.onMessagePartDelta = handleMessagePartDelta
sseManager.onMessageRemoved = handleMessageRemoved
sseManager.onMessagePartRemoved = handleMessagePartRemoved
sseManager.onSessionUpdate = handleSessionUpdate
sseManager.onSessionCompacted = handleSessionCompacted
sseManager.onSessionDeleted = handleSessionDeleted
sseManager.onSessionError = handleSessionError
sseManager.onSessionIdle = handleSessionIdle
sseManager.onSessionStatus = handleSessionStatus
sseManager.onTuiToast = handleTuiToast
sseManager.onPermissionUpdated = handlePermissionUpdated
sseManager.onPermissionReplied = handlePermissionReplied
sseManager.onQuestionAsked = handleQuestionAsked
sseManager.onQuestionAnswered = handleQuestionAnswered

export {
  abortSession,
  activeParentSessionId,
  activeSessionId,
  agents,
  clearActiveSession,
  clearActiveParentSession,
  clearInstanceSessionSelection,
  clearInstanceDraftPromptValues,
  clearInstanceDraftPrompts,
  clearSessionDraftPrompt,
  createSession,
  deleteSession,
  ensureSessionParentExpanded,
  executeCustomCommand,
  renameSession,
  runShellCommand,
  fetchAgents,
  fetchProviders,
  fetchSessions,
  loadMoreSessions,
  searchSessions,
  forkSession,
  getActiveParentSession,
  getActiveSession,
  getChildSessions,
  getDescendantSessions,
  getSessionRoot,
  getDefaultModel,
  getParentSessions,
  getSessionDraftPrompt,
  getSessionDraftPromptsForInstance,
  getAuthoritativeDraftSessionIdsForInstance,
  getAuthoritativelyDeletedSessionIdsForInstance,
  hasAuthoritativeSessionSelection,
  hydrateActiveSessionSelection,
  hydrateSessionIdleMarkers,
  hydrateSessionGenerationRecovery,
  beginSessionGenerationAdmission,
  cancelSessionGenerationAdmissions,
  getSessionFamily,
  getSessionInfo,
  getSessionMessagesLoadError,
  getSessionSearchQuery,
  getSessionSearchThreads,
  getSessionThreads,
  getThreadTotals,
  getSessions,
  getVisibleSessionIds,
  isSessionBusy,
  isSessionMessagesLoading,
  isSessionParentExpanded,
  loadMessages,
  loading,
  markSessionIdleSeen,
  markViewedSessionIdleSeen,
  providers,
  sendMessage,
  sessionInfoByInstance,
  sessions,
  setActiveParentSession,
  setActiveSession,
  setActiveSessionFromList,
  setSessionDraftPrompt,
  setSessionParentExpanded,
  setSessionStatus,
  toggleSessionParentExpanded,
  updateSessionAgent,
  updateSessionModel,
  clearSessionSearch,
  getSessionHasMore,
  hydrateSessionDraftPrompt,
  isSessionSearchLoading,
  onSessionDraftHydrated,
  resetSessionPagination,
  clearInstanceDeletedSessionAuthority,
}
export type { SessionInfo }
